//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingTools_371.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewTag
    {
        public int ReviewTagsId { get; set; }
        public int ReviewId { get; set; }
        public int TagId { get; set; }
    
        public virtual Review Review { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
