//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingTools_371.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Review()
        {
            this.ReviewTags = new HashSet<ReviewTag>();
        }
    
        public int ReviewId { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public string Content { get; set; }
        public int ToolID { get; set; }
        public int CreatorID { get; set; }
        public string Title { get; set; }
    
        public virtual Tool Tool { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewTag> ReviewTags { get; set; }
    }
}
